export const data = [
	{
		id: 1,
		initials: 'A',
		image: '/bad/image/url.jpg',
		fallbackIcon: 'standard:avatar',
		altText: 'Avatar',
		className: '',
		variant: 'circle',
		size: 'medium',
		backgroundColor: 'Blue',
	},
	{
		id: 2,
		initials: 'B',
		image: '/bad/image/url.jpg',
		fallbackIcon: 'standard:avatar',
		altText: 'Avatar',
		className: '',
		variant: 'circle',
		size: 'medium',
		backgroundColor: 'Purple',
	},
	{
		id: 3,
		initials: 'C',
		image: '/bad/image/url.jpg',
		fallbackIcon: 'standard:avatar',
		altText: 'Avatar',
		className: '',
		variant: 'circle',
		size: 'medium',
		backgroundColor: 'Yellow',
	},
	{
		id: 4,
		initials: 'D',
		image: '/bad/image/url.jpg',
		fallbackIcon: 'standard:avatar',
		altText: 'Avatar',
		className: '',
		variant: 'circle',
		size: 'medium',
		backgroundColor: 'Grey',
	},
	{
		id: 5,
		initials: 'E',
		image: '/bad/image/url.jpg',
		fallbackIcon: 'standard:avatar',
		altText: 'Avatar',
		className: '',
		variant: 'circle',
		size: 'medium',
		backgroundColor: 'Blue',
	},
	{
		id: 6,
		initials: 'F',
		image: '/bad/image/url.jpg',
		fallbackIcon: 'standard:avatar',
		altText: 'Avatar',
		className: '',
		variant: 'circle',
		size: 'medium',
		backgroundColor: 'Yellow',
	},
];

export default data;
